### PR TITLE
Remove dependency on `ScrollResponder.Mixin`

### PR DESCRIPTION
**Pull request by kacieb**
deprecated-react-native-listview has a dependency on ScrollResponder.Mixin which is an implementation detail of ScrollView in React Native. Since mixins have been long deprecated, we want to remove ScrollResponder from React Native.

To keep this deprecated listview working, this PR copies the contents of ScrollResponder into deprecated-react-native-listview (with minor changes to the import declarations to make them work outside of React Native). You can see the original contents of ScrollResponder.js [here](https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollResponder.js).

Tested with flow.

### CODE REVIEW

**Comment by yungsters** [comment]
Double check that all new dependencies that are not in the React Native Public API are okay for this package to now depend on. This seems fine to me, though.

**Review by yungsters — APPROVED** [review]

**Comment by kacieb** [comment]
> Double check that all new dependencies that are not in the React Native Public API are okay for this package to now depend on. This seems fine to me, though.

Is there a good way to check this? I did test the component to make sure it doesn't break when used, but I'm not sure how to make sure the new dependencies are all ok.

**Comment by TheSavior** [comment]
Maybe what Tim is saying is that now that it isn't importing ScrollResponder and is now importing these direct files:

```
react-native/Libraries/Interaction/FrameRateLogger
react-native/Libraries/Components/TextInput/TextInputState
react-native/Libraries/Renderer/shims/ReactNativeTypes
react-native/Libraries/Types/CoreEventTypes
react-native/Libraries/vendor/emitter/EventEmitter
react-native/Libraries/Components/Keyboard/Keyboard
react-native/Libraries/Components/ScrollView/ScrollView
react-native/Libraries/Components/ScrollView/ScrollViewCommands
```

Which means that any refactors we make to React Native in these files that we would have assumed would be internal only have the potential to break this package now.

It might still be the right tradeoff in the short term, but we should be aware and careful of the implications this will likely have on the team and make sure we don't leave it long term.

**Review by TheSavior — APPROVED** [review]

**Comment by kacieb** [comment]
Ah that makes sense. Thank you for the explanation. Yeah that's certainly not ideal. I think since ScrollResponder.Mixin was already internal, this isn't too much worse (other than dependencies on more quantity of things).

I think it would be a good idea to work on getting rid of usages of this package so we can stop using it. Once Facebook doesn't need this anymore, we could drop support entirely and just mark it as incompatible with the most recent versions of React Native so we don't need to continue to support it.

**Pull request merged**
