### PR TITLE
Rename windows fork of deprecated-props to cross-plat

### PR DESCRIPTION
**Pull request by rectified95**
RNW also has the .win32 extension, change to plain .js to reflect that, since the file contents would be the same and

### CODE REVIEW

**Comment by rectified95** [comment]
cc @yungsters

**Comment by yungsters** [comment]
Can we also get rid of the `*.ios.js` file, then?

**Comment by rectified95** [comment]
We could yeah, I'll push an update

**Comment by rectified95** [comment]
@yungsters Done

**Comment by yungsters** [comment]
@rectified95, published as v2.3.0. Thanks again.

**Pull request merged**
